# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Hi, I'm Nick
#tagline:          ''
description:      'The personal website of Nick Steele'
url:              https://nsteele2.github.io/blog/
baseurl:          /blog/ 

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         1

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
